[package]
name = "next_ev"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0", features = ["derive"] }
chrono = "0.4.22"
strum = "0.17.1"
strum_macros = "0.17.1"